In [2]:
import numpy as np

# List vs **Array**

In [ ]:
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
y=[1,2,3,4,5]
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


# Array **Creation**

In [ ]:
# x=[1,2,3,4,5]
# y=np.array(x)
# print(y)
y=np.array([1,2,3,4,5])
print(y)
print(y.ndim)
y

[1 2 3 4 5]
1


array([1, 2, 3, 4, 5])

In [ ]:
l=[]
for i in range(1,5):
  int_1=int(input('Enter: '))
  l.append(int_1)
print(np.array(l))

Enter: 2
Enter: 4
Enter: 6
Enter: 8
[2 4 6 8]


In [ ]:
# 2D array
ar2=np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
# 3D array
ar3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
# MultiDimensional Array
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# **Special Types of Arrays**

In [ ]:
# zeros(0) array
ar_zero=np.zeros(4)
print(ar_zero)
print()
# 3d zeros(0) array
ar_zero3=np.zeros((3,4))
print(ar_zero3)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Ones(1) array
ar_ones=np.ones(4)
print(ar_ones)
print()
# 3d ones(1) array
ar_ones3=np.ones((3,4))
print(ar_ones3)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Empty array
ar_empty = np.empty(4)
print(ar_empty)

[1. 1. 1. 1.]


In [ ]:
# Range array
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


In [ ]:
# Digonal array
ar_dia=np.eye(3)
print(ar_dia)
print()
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
# Linespace array
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# **Arrays with Random Numbers**

In [ ]:
# Rand() Function(0-1)
var=np.random.rand(4)
print(var)
print()
var1 = np.random.rand(2,5)
print(var1)

[0.16241319 0.35350492 0.88389637 0.95967956]

[[0.46039739 0.33700991 0.88516204 0.54524494 0.08916011]
 [0.16123232 0.83041665 0.14682823 0.99793235 0.83203804]]


In [ ]:
# Randn() Function(+ve,-ve,closet to zero)
var=np.random.randn(5)
print(var)

[-0.58120061 -0.31697056  0.19532388  0.24972422 -0.2801932 ]


In [ ]:
# Randf() Function(0.0,1.0)
var = np.random.ranf(4)
print(var)

[0.11133086 0.7261791  0.61621294 0.20840374]


In [ ]:
# Randint() Function in given range
var=np.random.randint(5,20,8)
print(var)

[11 18  5 12  8  5 10 12]


# **Shape**

In [ ]:
# Shape
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape) # tells rows and columns

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [ ]:
 var1=np.array([1,2,3,4],ndmin=4)
 print(var1)
 print(var1.ndim)
 print()
 print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# **Reshape**

In [ ]:
var=np.array([1,2,3,4,5,6])
print(var)
x=var.reshape(3,2)
print(x)
print('Dimension=',x.ndim)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
Dimension= 2


In [ ]:
var=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
x=var.reshape(2,3,2)
print(x)
print('Dimension=',x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension= 3


In [ ]:
var=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var.reshape(2,3,2)
print(x)
print('Dimension=',x.ndim)
print()
one=x.reshape(-1)
print(one)
print('Dimension=',one.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension= 3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension= 1


# **Airtmetic Operations**

In [ ]:
# 1D Array
var = np.array([1,2,3,4])
varadd=var+3
print(varadd)
var = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
# varadd=np.add(var,var2)
varadd=var+var2
print(varadd)

[4 5 6 7]
[2 4 6 8]


In [ ]:
# 2D Array
var=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[1,2,3,4]])
varadd= var + var2
print(var,"\n + \n",var2)
print('\n',varadd)

[[1 2 3 4]
 [1 2 3 4]] 
 + 
 [[1 2 3 4]
 [1 2 3 4]]

 [[2 4 6 8]
 [2 4 6 8]]


In [ ]:
# 1D Array
var = np.array([3,2,1,4,5,3,2])
print('Min: ',np.min(var))
print('Max: ',np.max(var))
print('Min Position: ',np.argmin(var))
print('Max Position: ',np.argmax(var))
print('sqrt: ',np.sqrt(var))
print('Comunity Sum: ',np.cumsum(var))

Min:  1
Max:  5
Min Position:  2
Max Position:  4
sqrt:  [1.73205081 1.41421356 1.         2.         2.23606798 1.73205081
 1.41421356]
Comunity Sum:  [ 3  5  6 10 15 18 20]


In [ ]:
# 2D Array
var = np.array([[2,1,3],[9,5,6]])
print('Min: ',np.min(var,axis=1))
print('Min: ',np.min(var,axis=0))
print('Comunity Sum: ',np.cumsum(var))

Min:  [1 5]
Min:  [2 1 3]
Comunity Sum:  [ 2  3  6 15 20 26]


# **Broadcasting with Numpy Arrays**

In [ ]:
var=np.array([1,2,3,4])
print(var)
print(var.shape)
print()
var2=np.array([[1],[2],[3],[4]])
print(var2)
print(var2.shape)
print(var+var2) #(1x3)+(3x1)

[1 2 3 4]
(4,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [ ]:
x=np.array([[1],[2]])
print(x)
print(x.shape)
print()
y=np.array([[1,2,3],[1,2,3]])
print(y)
print(y.shape)
print('\n',x+y) #(2X1)+(2X3)

[[1]
 [2]]
(2, 1)

[[1 2 3]
 [1 2 3]]
(2, 3)

 [[2 3 4]
 [3 4 5]]


# **Indexing**

In [ ]:
# 1D Array
var = np.array([9,8,7,6])
print(var[0])
print(var[-1])

9
6


In [ ]:
# 2D Array
var = np.array([[9,8,7],[4,5,6]])
print(var)
print(var[0,2])

[[9 8 7]
 [4 5 6]]
7


In [ ]:
# 3D Array
var = np.array([[[1,2],[6,7]]])
print(var)
print(var[0,1,1])

[[[1 2]
  [6 7]]]
7


# **Slicing**

In [ ]:
# 1D Array
var = np.array([1,2,3,4,5,6,7])
print(var)
print('2 to 5: ',var[1:5])
print('2 to End: ',var[1:])
print('1 to 5: ',var[:5])
print('step: ',var[::2])
print('step: ',var[1:4:2])

[1 2 3 4 5 6 7]
2 to 5:  [2 3 4 5]
2 to End:  [2 3 4 5 6 7]
1 to 5:  [1 2 3 4 5]
step:  [1 3 5 7]
step:  [2 4]


In [ ]:
# 2D Array
var = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var)
print()
print('8 to 5: ',var[1,1:])
print('12 to 15: ',var[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5:  [8 7 6 5]
12 to 15:  [12 13 14 15]


# **Iterating Arrays**

In [ ]:
# 1D  Array
var=np.array([9,8,7,6,5,4,3])
print(var)
for i in var:
  print(i)

[9 8 7 6 5 4 3]
9
8
7
6
5
4
3


In [ ]:
# 2D Array
var = np.array([[1,2,3,4],[9,8,7,6]])
print(var,'\n')
for j in var:
  print(j)
print()
for i in var:
  for j in i:
    print(j)

[[1 2 3 4]
 [9 8 7 6]] 

[1 2 3 4]
[9 8 7 6]

1
2
3
4
9
8
7
6


In [ ]:
# 3D Array
var = np.array([[[3,2,1],[6,5,4]]])
print(var)
print()
# for i in var:
#   for j in i:
#     for k in j:
#       print(k)
for i in np.nditer(var):
  print(i)
print()
for i in np.ndenumerate(var):
  print(i)

[[[3 2 1]
  [6 5 4]]]

3
2
1
6
5
4

((0, 0, 0), 3)
((0, 0, 1), 2)
((0, 0, 2), 1)
((0, 1, 0), 6)
((0, 1, 1), 5)
((0, 1, 2), 4)


# **Copy and View**

In [ ]:
var = np.array([1,2,3,4])
co=var.copy()
print('var: ',var)
print('copy: ',co)
co[1]=40
print()
print('var: ',var)
print('copy: ',co)


var:  [1 2 3 4]
copy:  [1 2 3 4]

var:  [1 2 3 4]
copy:  [ 1 40  3  4]


In [ ]:
var = np.array([1,2,3,4])
vi=var.view()
print('var: ',var)
print('View: ',vi)
vi[1]=40
print()
print('var: ',var)
print('View: ',vi)

var:  [1 2 3 4]
View:  [1 2 3 4]

var:  [ 1 40  3  4]
View:  [ 1 40  3  4]


# **Join Array**

In [ ]:
# 1D Array
var = np.array([1,2,3,4])
var2= np.array([5,6,7,8])
ar= np.concatenate((var,var2))
print('var: ',var)
print('var2: ',var2)
print('ar: ',ar)

var:  [1 2 3 4]
var2:  [5 6 7 8]
ar:  [1 2 3 4 5 6 7 8]


In [ ]:
# 2D Array
var = np.array([[1,2],[3,4]])
var2= np.array([[5,6],[7,8]])
ar= np.concatenate((var,var2),axis=1)
print('var: \n',var)
print('var2: \n',var2)
print('ar: \n',ar)

var: 
 [[1 2]
 [3 4]]
var2: 
 [[5 6]
 [7 8]]
ar: 
 [[1 2 5 6]
 [3 4 7 8]]


# **Split Array**

In [ ]:
# 1D Array
var= np.array([1,2,3,4,5,6])
print(var)
ar=np.array_split(var,3)
print('\n',ar)
print(ar[1])

[1 2 3 4 5 6]

 [array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


In [ ]:
# 2D Array
var=np.array([[1,2],[3,4],[5,6]])
print(var)
ar=np.array_split(var,3)
print('\n',ar)
print(ar[1])

[[1 2]
 [3 4]
 [5 6]]

 [array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[[3 4]]


# **Search**

In [6]:
var = np.array([1,2,3,4,2,5,2,5,6,7])
print(np.where(var==2))
print(np.where(var%2==0))

(array([1, 4, 6]),)
(array([1, 3, 4, 6, 8]),)


In [7]:
var = np.array([1,2,3,4,6,7,8])
print(np.searchsorted(var,5))


4


# **Sort**

In [10]:
# 1D Array
var = np.array([4,2,3,1,12,5,22,52,6,7])
print(np.sort(var))
var = np.array(['a','s','d','f'])
print(np.sort(var))

[ 1  2  3  4  5  6  7 12 22 52]
['a' 'd' 'f' 's']


In [11]:
# 2D Array
var=np.array([[4,2,3],[1,12,5],[22,52,6]])
print(np.sort(var))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


# **Filter**

In [12]:
var=np.array(['a','s','d','f'])
f=[True,False,False,True]
new=var[f]
print(new)

['a' 'f']


# **Shuffle**

In [14]:
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[2 1 5 3 4]


# **Unique**

In [16]:
var=np.array([1,2,3,4,2,5,2,6,2,7])
x=np.unique(var,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([1, 4, 1, 1, 1, 1, 1]))


# **Resize**

In [17]:
var=np.array([1,2,3,4,5,6])
y=np.resize(var,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


# **Flatten & Ravel**

In [19]:
var=np.array([1,2,3,4,5,6])
y=np.resize(var,(2,3))
print(y)
print(y.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [20]:
var=np.array([1,2,3,4,5,6])
y=np.resize(var,(2,3))
print(y)
print(y.ravel())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# **Insert**

In [24]:
var=np.array([1,2,3,4])
print(var)
y=np.insert(var,(2,4),40)
print(y)

[1 2 3 4]
[ 1  2 40  3  4 40]


# **Delete**

In [26]:
var=np.array([1,2,3,4])
print(var)
d=np.delete(var,2)
print(d)

[1 2 3 4]
[1 2 4]


# **Matrix**

In [35]:
var=np.matrix([[1,2,3],[1,2,3],[1,2,3]])
var2=np.matrix([[1,2,3],[1,2,3],[1,2,3]])
print(var)
print(type(var))
print()
print(var+var2)
print()
print(var-var2)
print()
print(var.dot(var2))


[[1 2 3]
 [1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[2 4 6]
 [2 4 6]
 [2 4 6]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [37]:
var=np.array([[1,2,3],[1,2,3]])
var2=np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))
print()
print(var+var2)
print()
print(var-var2)
print()
print(var*var2)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[2 4 6]
 [2 4 6]]

[[0 0 0]
 [0 0 0]]

[[1 4 9]
 [1 4 9]]


# **Matrix Function**

In [39]:
# Transpose
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()

print(np.transpose(var))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [41]:
# Swapaxes
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()

print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [43]:
# Inverse
var = np.matrix([[1,2],[3,4]])
print(var)
print()

print(np.linalg.inv(var))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [46]:
# Power of Matrix
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.matrix_power(var,2))
print()
print(np.linalg.matrix_power(var,0))
print()
print(np.linalg.matrix_power(var,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [50]:
# Determinant
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.det(var))
print()
var = np.matrix([[1,2,3],[3,4,3],[4,5,6]])
print(var)
print()
print(np.linalg.det(var))

[[1 2]
 [3 4]]

-2.0000000000000004

[[1 2 3]
 [3 4 3]
 [4 5 6]]

-6.0
